### ISSUE TITLE
Cydia Impactor With CydiaLoader LATEST error provision.cpp:81

### ISSUE THREAD

**Issue by gavO852** [nonymoosee/CydiaImpactorLoader#2]
When telling CydiaLoader to open Cydia Impactor and install the selected IPA, Cydia Impactor gives the provision.cpp:81 error, An App ID with identifier com.google.ios.youtube is not available please enter a different string. When just using Cydia Impactor MANUALLY no errors come up.
![error](https://user-images.githubusercontent.com/35172725/34641501-1e9b98ba-f2cb-11e7-87e5-68a16f754462.jpg)

**Comment by nonymoosee** [comment]
Are you using the most up to date version of the software? It might need longer pauses based on each machine, but that’s weird because it waits for specific boxes before entering in the text..

**Comment by nonymoosee** [comment]
Can you try the newest version I posted today? :)

**Comment by gavO852** [comment]
Yes. I will try when I get back from a school meeting today.

**Comment by vanlvy** [comment]
tested Loaderv2.4 is fine. you can try remove the Certificates.
Open Cydia Impactor Click "Xcode"> "Revoke Certificates".

**Comment by nonymoosee** [comment]
Let me know if this problem is still popping up for you.

**Comment by gavO852** [comment]
Still gives me the same error.

**Comment by nonymoosee** [comment]
Can you try a different IPA please?

**Comment by nonymoosee** [comment]
Also if you are attempting to install YouTube or YouTube ++ please make sure you delete all installs of it on your phone before trying again

**Comment by gavO852** [comment]
Yea.

**Comment by nonymoosee** [comment]
If you want me to look at it directly via Teamviewer then leave me an email to contact you at
