### ISSUE TITLE
Autofills password even after deleting Cydiaimpactorloader

### ISSUE THREAD

**Issue by mesailesh7** [nonymoosee/CydiaImpactorLoader#4]
I faced some problem with it so I deleted Cydiaimpactorloader but even after deleting it , my cydia impactor is still auto filling Apple id and password and showing error password and id don't match eventhough I haven't entered anything..... 
Is there anyway that I can start Cydiaimpactor as new. Just FYI I have already deleted CydiaimpactorLoader and Cydia impactor files and downloaded the latest Cydia impactor version but  problem still continues.
Now as an alternative I am using Superimpactor but It is not good as Cydia Impactor so I hope you would be able to help me.

Thanks in advance

**Comment by nonymoosee** [comment]
You probably ran it multiple times, in the button right of your screen you should see multiple icons, just right click on then and close then. Or just log off and log back on.

**Comment by nonymoosee** [comment]
Also if you want to explain the problems I can try and help you

**Comment by mesailesh7** [comment]
![capture](https://user-images.githubusercontent.com/37073011/37018157-72d05a3a-213b-11e8-8a05-7404cc3ddc9b.JPG)

actually as you have aforementioned yes i ran it multiple times and I noticed in my bottom right there were multiple icons which i manually closed all of them and even I restarted my Laptop but still my problem persist. I have attached an image for your ease, Hope it will make a little more clear to you.Furthermore eventhough I haven't used cydialoader cydiaimpactor is not showing "enter id and enter  password" option and directly it is popping out provision cpp:173 error

**Comment by nonymoosee** [comment]
Have you saved your username and password via Regedit? Unless you run the program.. it doesn’t auto fill the password...? Just deleted CydiaImpactorLoaded, easy.

**Comment by mesailesh7** [comment]
Nope haven't done anything from Regedit,
But thank you for your response, I think I will just restore my Laptop. Hope that will Fix it.
Keep up the good work ^_^

**Comment by nonymoosee** [comment]
Oh! I just remembered, delete all the certificates in that folder and use the “revoke certificates” function or something like that, it will fix it. Just so you know my program doesn’t install anything and doesn’t keep filling stuff in unless it’s running.

**Comment by mesailesh7** [comment]
O_O by certificates if you mean password and Id .txt file . I already deleted it but still cydia impactor doesn't ask for my password or id. I think I messed up something with cydia impactor and ur program cannot be blamed for it so i will do what every noob does restore 😂😂😂 I am pretty sure it will resolve it 😇

**Comment by nonymoosee** [comment]
No I mean the little icons in the folder that look like diploma things.. also go to through the impact or menu and you will see something like revoke blah blah.. run that and try again, restore shouldn’t be needed and it also might not fix it.

**Comment by mesailesh7** [comment]
![capture](https://user-images.githubusercontent.com/37073011/37143864-77558666-22e4-11e8-9538-6482972e6d86.JPG)

oh.. there are not any diploma like things...PFA
and recently I have noticed that in my laptop there are other window users accounts as well like my brothers and today when i tried installing an app through cydia impactor from his windows user , cydia impactor popped up "Please insert user id and then password option as well" so any idea why in my user only it is not popping out user id and password option. Or shall I just restore my laptop I am pretty sure it will solve my problem

**Comment by nonymoosee** [comment]
You’re welcome to restore but I would try the revoke option first to see if it fixes everything.. also you said you deleted my app but it’s right there?

**Comment by mesailesh7** [comment]
I already tried revoke option but luck was not on my side so unfortunately it didn't worked out. Oh yes I deleted your app but I was trying for the last time hoping some magic would happen and it might start working hehe but It didn't.  Thanks for all your support , Highly appreciated ^_^

**Comment by nonymoosee** [comment]
Yeah sorry dude
